In [1]:
# K-Means Clustering with Iris Dataset
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
#Import Dataset
data = pd.read_csv("/Users/ashutosh/datasets/Iris/iris.csv")

In [25]:
data.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [26]:
data.species.unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [6]:
from sklearn.cluster import KMeans
X = data.drop(['species'],axis=1)
y=data['species']

In [9]:
kmeans = KMeans(n_clusters=3,random_state=3)
cluster = kmeans.fit(X)


In [11]:
cluster.labels_

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 0, 0,
       2, 2, 2, 2, 0, 2, 0, 2, 0, 2, 2, 0, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2,
       0, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 0], dtype=int32)

In [27]:
def cat_to_label(category):
    if category==2:
        return 'setosa'
    elif category==1:
        return 'versicolor'
    elif category==0:
        return 'virginica'
    else:
        return 'None'

y_pred = pd.Series([cat_to_label(category) for category in cluster.labels_])
    
        

In [28]:
y_pred.unique()

array(['versicolor', 'virginica', 'setosa'], dtype=object)

In [32]:
data['species'].value_counts()

versicolor    50
setosa        50
virginica     50
Name: species, dtype: int64

ModuleNotFoundError: No module named 'keras'

In [29]:
y_pred.value_counts()

virginica     62
versicolor    50
setosa        38
dtype: int64

In [30]:
from sklearn.metrics import confusion_matrix, classification_report
print(confusion_matrix(y, y_pred))
print(classification_report(y, y_pred))

[[ 0 50  0]
 [ 2  0 48]
 [36  0 14]]
             precision    recall  f1-score   support

     setosa       0.00      0.00      0.00        50
 versicolor       0.00      0.00      0.00        50
  virginica       0.23      0.28      0.25        50

avg / total       0.08      0.09      0.08       150

